# Generated by Django 3.2 on 2022-04-24 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
